version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mysql-jobfinder
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3301:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
